# docker-compose.yml
version: '3'

services:
  backend:
    build: ./backend/app
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend/disease_prediction
    ports:
      - "3000:80"
